# properties.py — Real listings from Gurgaon, Hyderabad, Kolkata & Mumbai
# Auto-generated from your CSV data

PROPERTIES = [
    {
        "name": "Paras Quartier",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Gwal Pahari",
        "bhk": "4BHK",
        "area": "6000 sq.ft.",
        "price": "₹9 Crore",
        "furnish": "Unfurnished",
        "status": "READY TO MOVE, NEW BOOKING, RERA",
        "description": "Let your dream of owning a flat come true with Paras Quartier. It offers an exclusive range of 4 BHK flats in Gwal Pahari, Gurgaon. We bring you an amazing deal of a 4 BHK that is currently available at price of Rs. 9 Crore and has a super built-up area of 6000.0 sq. ft.   Paras Quartier is a secure",
    },
    {
        "name": "Gulmohar Apartment",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Sector 56 Gurgaon",
        "bhk": "3BHK",
        "area": "2200 sq.ft.",
        "price": "₹1.75 Crore",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Situated in sector 56 gurgaon, gulmohar apartment is a well planned society that offers a pleasant living experience to its residents. This 3 bhk flat in gurgaon is your opportunity to be a part of this community. Containing 3 bedroom(s), 3 bathrooms and more than 3 balconies, this flat is spread ov",
    },
    {
        "name": "Vatika One Express City",
        "type": "Residential Land",
        "city": "Gurgaon",
        "locality": "Sector 88 Gurgaon",
        "bhk": "N/A",
        "area": "1620 sq.ft.",
        "price": "₹2.16 Crore",
        "furnish": "Unfurnished",
        "status": "NORTH-EAST FACING, HUDA APPROVED, IN GATED COMMUNITY, UNDER CONSTRUCTION, RESALE",
        "description": "180 sq.Yds plot on sale at vatika express city sector 88b gurgaon, rera approved project, excellent location, possession very soon, adjoining main dwarka express way, nearby patudi -Rewari highway. Please call for the visit",
    },
    {
        "name": "Ireo City Plots",
        "type": "Residential Land",
        "city": "Gurgaon",
        "locality": "Sector 60 Gurgaon",
        "bhk": "N/A",
        "area": "3240 sq.ft.",
        "price": "₹7.25 Crore",
        "furnish": "Unfurnished",
        "status": "CORNER PROPERTY, IN GATED COMMUNITY, READY TO MOVE, RESALE",
        "description": "Excellent plot for sale in ireo city township located on main 60 metre sector road golf course extension road gurgaon its corner plot east facing near central park .",
    },
    {
        "name": "Suncity Vatsal Valley",
        "type": "Independent/Builder Floor",
        "city": "Gurgaon",
        "locality": "Gwal Pahari",
        "bhk": "3BHK",
        "area": "1430 sq.ft.",
        "price": "₹1.65 Crore",
        "furnish": "Semifurnished",
        "status": "UNDER CONSTRUCTION, RESALE, RERA",
        "description": "The best projectsector 2 gwal pahari size 1430 type 3bhk semi furnished modular kitchan with ac. Wardrove",
    },
    {
        "name": "New Greenwood Society",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Sector 52 Gurgaon",
        "bhk": "4BHK",
        "area": "3400 sq.ft.",
        "price": "₹2.55 Crore",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Situated in sector 52 gurgaon, new greenwood society is a well planned society that offers a pleasant living experience to its residents. This 4 bhk flat in gurgaon is your opportunity to be a part of this community. Containing 4 bedroom(s), 4 bathrooms and more than 3 balconies, this flat is spread",
    },
    {
        "name": "Satya The Hermitage",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Sector 103 Gurgaon",
        "bhk": "3BHK",
        "area": "1991 sq.ft.",
        "price": "₹1.1 Crore",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Available a very good deal of 3 bhk plus servant room spacious apartment in satya the hermitage society luxury project. The project offers 75% open area with indulgent greens letting you enjoy the gifts of mother nature in all its serenity. Grand, well-Appointed, air-Conditioned entrance lobbies for",
    },
    {
        "name": "M3M Heights",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Sector 65 Gurgaon",
        "bhk": "3BHK",
        "area": "1932 sq.ft.",
        "price": "₹2.61 Crore",
        "furnish": "Furnished",
        "status": "UNDER CONSTRUCTION, RESALE, RERA",
        "description": "M3m heights in sector-65 gurgaon, gurgaon by m3m india is a residential project. The project offers an apartment with the perfect combination of contemporary architecture and features to provide a comfortable living. M3m heights offers facilities such as gymnasium and lift. Also has amenities like a",
    },
    {
        "name": "Ansals Sushant Floors",
        "type": "Independent/Builder Floor",
        "city": "Gurgaon",
        "locality": "Sushant Lok Phase 2",
        "bhk": "4BHK",
        "area": "2880 sq.ft.",
        "price": "₹1.9 Crore",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Italian marble flooring,  Stilt parking,  One room wooden tile flooring 24 washroom tiles Front and back upvc doors and windows Havells/finolex wires Havells swittch / l&t Jaguar sanitary fittings,  Modular kitchen, Drawing and dining room Pooja room Luxury look with a1 quality work Covered parking ",
    },
    {
        "name": "M3M Soulitude",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Sector 89 Gurgaon",
        "bhk": "3BHK",
        "area": "1423 sq.ft.",
        "price": "₹1.2 Crore",
        "furnish": "Semifurnished",
        "status": "UNDER CONSTRUCTION, RESALE, RERA",
        "description": "M3m soulitude is one of gurgaon\\'s most sought after destination for apartments and this 3 bhk flat in sector 89 gurgaon is your opportunity to be a part of this community. The flat is east-Facing. The flat occupies a super built up area of 1423 sq.Ft. That consists of 3 bedrooms, 3 bathrooms and 2 b",
    },
    {
        "name": "Block C",
        "type": "Independent/Builder Floor",
        "city": "Gurgaon",
        "locality": "Palam Vihar",
        "bhk": "3BHK",
        "area": "1700 sq.ft.",
        "price": "₹1.2 Crore",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Upcoming metro station just 200 metres only  2 badminton cout Yoga center",
    },
    {
        "name": "TDI Ourania",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Sector 53 Gurgaon",
        "bhk": "4BHK",
        "area": "3850 sq.ft.",
        "price": "₹4.95 Crore",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Looking for a 4 bhk property for sale in gurgaon? Buy this 4 bhk flat in tdi ourania that is situated in sector 53 gurgaon. This property faces the north direction. Containing 4 bedroom(s), 5 bathrooms and 3 balconies, this flat is spread over a super built up area of 3850 sq.Ft. The residential bui",
    },
    {
        "name": "Greenopolis",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Sector 89 Gurgaon",
        "bhk": "3BHK",
        "area": "1957 sq.ft.",
        "price": "₹1.25 Crore",
        "furnish": "Furnished",
        "status": "READY TO MOVE, RESALE, RERA",
        "description": "Check out this 3 bhk apartment for sale in greenopolis, a popular residential project that houses in-Demand flats in sector 89 gurgaon. This is a south-West-Facing property. The flat is over 1957 sq.Ft. Super built up area and comes with 3 bedroom(s), 3 bathrooms and 3 balconies. The residential bui",
    },
    {
        "name": "Central Park Resort Belgravia Residences",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Sector 48 Gurgaon",
        "bhk": "3BHK",
        "area": "2464 sq.ft.",
        "price": "₹5.5 Crore",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "80.94k sq.M grand central garden Easy connectivity through huda city centre metro Masterplanned by renowned hok international ltd. 24.43% price appreciation in the last 1 year Properties with 100% power backup available",
    },
    {
        "name": "Godrage meriden Gurugram",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Sector 102 Gurgaon",
        "bhk": "3BHK",
        "area": "1855 sq.ft.",
        "price": "₹2.63 Crore",
        "furnish": "Semifurnished",
        "status": "UNDER CONSTRUCTION, RESALE",
        "description": "Located in the popular residential address of sector 102 gurgaon, godrage meriden gurugram is one of the most preferred destination for apartments in gurgaon. This 3 bhk flat is your ticket to be a part of this community. The flat is facing the east direction. The flat occupies a carpet area of 1855",
    },
    {
        "name": "Ansal API Spanish Court",
        "type": "Independent House/Villa",
        "city": "Gurgaon",
        "locality": "Palam Vihar",
        "bhk": "4BHK",
        "area": "1557 sq.ft.",
        "price": "₹2.9 Crore",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "On sale 173 sq yrds built up house park facing. 2. Bedroom attach bathroom plus dine dining modular kitchen complete wooden work more detailes cont sandeep sanya estate",
    },
    {
        "name": "Godrej Aria",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Sector 79 Gurgaon",
        "bhk": "2BHK",
        "area": "2250 sq.ft.",
        "price": "₹1.56 Crore",
        "furnish": "Semifurnished",
        "status": "UNDER CONSTRUCTION, RESALE, RERA",
        "description": "Luxury homes in gurugram sector-79, sector-83, golf course road, sector 84 and many other options available along with this.  Give us chance to serve you once.",
    },
    {
        "name": "Luxury Residency",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Sector 15 Part 2",
        "bhk": "3BHK",
        "area": "2230 sq.ft.",
        "price": "₹3.33 Crore",
        "furnish": "Semifurnished",
        "status": "UNDER CONSTRUCTION, RESALE",
        "description": "Most promising residential Of 2023  3bhk + study size 2230sqft Most promising location in the heart of gurgaon  Sector 15- Part 2 Features  Shopping complex 5mins Airport 15mins Nh 48 3mins",
    },
    {
        "name": "Smart World Gems",
        "type": "Independent/Builder Floor",
        "city": "Gurgaon",
        "locality": "Sector 89 Gurgaon",
        "bhk": "2BHK",
        "area": "1103 sq.ft.",
        "price": "₹85 Lakh",
        "furnish": "Semifurnished",
        "status": "UNDER CONSTRUCTION, RESALE, RERA",
        "description": "Smart world gems by the smart world in sector 89 gurgaon city of dreams gurgaon is a gated housing community. It accommodates airy and well-Ventilated independent floors in gurugram. The thoughtful elegant floors in gurgaon assist you with excess comforts. This housing boulevard is all set to charm ",
    },
    {
        "name": "DLF Amaltas Drive",
        "type": "Independent/Builder Floor",
        "city": "Gurgaon",
        "locality": "DLF Phase 4",
        "bhk": "4BHK",
        "area": "1550 sq.ft.",
        "price": "₹5.5 Crore",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Looking for magnificent 4 bhk builder floors in dlf phase 4 gurgaon? This property is the best deal for you. This spacious builder floor provides you 4 bedrooms, 4 bathrooms and 2 balconies. This is a semi-Furnished builder floor. This builder floor provides you carpet area of 1550 sq.Ft. This build",
    },
    {
        "name": "DLF Park Place",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Sector 54 Gurgaon",
        "bhk": "3BHK",
        "area": "2300 sq.ft.",
        "price": "₹5.5 Crore",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "This 3 bhk flat in sector-54, gurgaon is available for sale. It is an east facing property and a part of dlf park place. This semifurnished flat is ready to move in. It is a 1-5 year old. It has 4 bathrooms. The furnishings include. The 3 balconies keep the apartment well ventilated. The apartment i",
    },
    {
        "name": "M3M The Marina",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Sector 68 Gurgaon",
        "bhk": "3BHK",
        "area": "1650 sq.ft.",
        "price": "₹1.45 Crore",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE, RERA",
        "description": "M3m the marina in sector 68, gurgaon is a ready-To-Move housing society. It offers apartments and independent floors in varied budget range. These units are a perfect combination of comfort and style, specifically designed to suit your requirements and conveniences. There are 2bhk, 3bhk and 4bhk apa",
    },
    {
        "name": "The Close South",
        "type": "Residential Apartment",
        "city": "Gurgaon",
        "locality": "Nirvana Country",
        "bhk": "3BHK",
        "area": "2531 sq.ft.",
        "price": "₹1.05 Lakh",
        "furnish": "Semifurnished",
        "status": "FURNISHED",
        "description": "This lovely 3 bhk apartment for rent in nirvana country is available in one of gurgaon\\'s most popular projects, the close south. This flat consists of 4 bathrooms & 3 balconies in 2300 sq.Ft. Super built-Up area. Flat is constructed on 2531 sq.Ft. You get an additional space of servant room. 2 cover",
    },
    {
        "name": "Dhyanish Towers",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Manikonda",
        "bhk": "3BHK",
        "area": "1475 sq.ft.",
        "price": "₹75 Lakh",
        "furnish": "Furnished",
        "status": "READY TO MOVE, RESALE",
        "description": "3bhk flat/apartment for sale in dhyanish towers hanuman nagar, manikonda, hyderabad, hyderabad Welcome to your dream home! We are delighted to present this exquisite unfurnished 3bhk residential apartment situated in dhyanish towers hanuman nagar, manikonda, hyderabad, hyderabad. This meticulously d",
    },
    {
        "name": "Prestige Beverly Hills",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Kokapet",
        "bhk": "3BHK",
        "area": "1103-1294  sq.ft.",
        "price": "₹1.2 Crore",
        "furnish": "Unfurnished",
        "status": "UNDER CONSTRUCTION, NEW BOOKING, RERA",
        "description": "Book your 3 BHK flat in Prestige Beverly Hills, Kokapet, Hyderabad. Having a carpet area of 1103.0 sq. ft. - 1294.0 sq. ft., these flats promise an exclusive view and refreshing vibes, making them well ventilated.  It is a superbly design project set amidst excellent surroundings and offers resident",
    },
    {
        "name": "Vijay appartments",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Kavadiguda",
        "bhk": "3BHK",
        "area": "1150 sq.ft.",
        "price": "₹63 Lakh",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "The property is located on main road kavadiguda very near commercial complex,public transport,malls , movie theatre,schools and it\\'s a happening place good for family and investment buyer",
    },
    {
        "name": "Modi Serene Park",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Ghatkesar",
        "bhk": "2BHK",
        "area": "905 sq.ft.",
        "price": "₹38 Lakh",
        "furnish": "Semifurnished",
        "status": "UNDER CONSTRUCTION, RESALE, RERA",
        "description": "2 bhk property at very prominent location",
    },
    {
        "name": "urbanrise/joypur",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Aminpur",
        "bhk": "3BHK",
        "area": "1333 sq.ft.",
        "price": "₹83 Lakh",
        "furnish": "Furnished",
        "status": "UNDER CONSTRUCTION, RESALE",
        "description": "Urbanrise/joypur is one of hyderabad\\'s most sought after destination for apartments and this 3 bhk flat in aminpur is your opportunity to be a part of this community. This residential flat is east-Facing direction. The floor plan additionally contains 3 bedroom(s), 3 bathrooms and 1 balcony. All in ",
    },
    {
        "name": "Candeur Crescent",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Gachibowli",
        "bhk": "3BHK",
        "area": "1333-2656  sq.ft.",
        "price": "₹2.05 Crore",
        "furnish": "Unfurnished",
        "status": "UNDER CONSTRUCTION, NEW BOOKING, RERA",
        "description": "Experience a new style of living with Candeur Crescent. The project offers an exclusive range of 3 BHK flats in Gachibowli, Hyderabad at a price range of Rs. 1.03 Crore - Rs. 2.05 Crore.  These flats have a super built-up area ranging from 1333.0 sq. ft. - 2656.0sq. ft. It is an under construction p",
    },
    {
        "name": "Beleza",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Gandimaisamma",
        "bhk": "2BHK",
        "area": "1159 sq.ft.",
        "price": "₹42.18 Lakh",
        "furnish": "Furnished",
        "status": "UNDER CONSTRUCTION, RESALE",
        "description": "A very good luxurious premium apartments located near gandimaisamma near bachupally high class amenities available friendly budget nice atmosphere nature",
    },
    {
        "name": "on request",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Gundlapochampalli",
        "bhk": "3BHK",
        "area": "1525 sq.ft.",
        "price": "₹92 Lakh",
        "furnish": "Furnished",
        "status": "UNDER CONSTRUCTION, RESALE",
        "description": "3 acers 260 units only , small town ship",
    },
    {
        "name": "Praneeth Pranav Leaf",
        "type": "Independent House/Villa",
        "city": "Hyderabad",
        "locality": "Mallampet",
        "bhk": "3BHK",
        "area": "1650 sq.ft.",
        "price": "₹1.85 Crore",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE, RERA",
        "description": "Stunning independent house villa for sale in praneeth pranav leaf, mallampet, hyderabad, hyderabad Introducing a magnificent independent house villa nestled in a prime location of mallampet, hyderabad. This exquisite property offers luxurious living combined with contemporary design and an array of ",
    },
    {
        "name": "velimela",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Velimela",
        "bhk": "2BHK",
        "area": "1323 sq.ft.",
        "price": "₹42.34 Lakh",
        "furnish": "Furnished",
        "status": "UNDER CONSTRUCTION, RESALE",
        "description": "Beside gaudium school  Very near to exit no 2 Near to serice road Near to gachibowli  Near to hitech city",
    },
    {
        "name": "KRISHNA KUNJ CENTRAL COURTY YARD",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Suchitra",
        "bhk": "4BHK",
        "area": "2115 sq.ft.",
        "price": "₹1.2 Crore",
        "furnish": "Furnished",
        "status": "UNDER CONSTRUCTION, RESALE",
        "description": "Check out this 4 bhk apartment for sale in krishna kunj central courty yard, a popular residential project that houses in-Demand flats in suchitra, secunderabad. The flat is facing the north-West direction. Constructed on a super built up area of 2115 sq.Ft., the flat comprises 4 bedroom(s), 3 bathr",
    },
    {
        "name": "Sree Kalpa Pristine",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Bachupally",
        "bhk": "3BHK",
        "area": "1315-1732  sq.ft.",
        "price": "₹1 Crore",
        "furnish": "Unfurnished",
        "status": "UNDER CONSTRUCTION, NEW LAUNCH, NEW BOOKING, RERA",
        "description": "Enjoy a blissful living experience in Sree Kalpa Pristine. This residential project encompasses 3 BHK flats in Bachupally, Hyderabad and brings you the best of both the worlds – excellent aesthetics and exemplary lifestyle.  Its unique highlights include facilities like  and many others. All of thes",
    },
    {
        "name": "Magna Ananda Villas",
        "type": "Independent House/Villa",
        "city": "Hyderabad",
        "locality": "Kollur",
        "bhk": "5BHK",
        "area": "520 sq.ft.",
        "price": "₹8.03 Crore",
        "furnish": "Furnished",
        "status": "UNDER CONSTRUCTION, RESALE",
        "description": "This is a ananda villas, osmannagar under construction, rera certified,1yr possision total 7acreas 45 villas, prime located g3,",
    },
    {
        "name": "SIGNATURE HOMES",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Kompally",
        "bhk": "3BHK",
        "area": "1960 sq.ft.",
        "price": "₹90.75 Lakh",
        "furnish": "Furnished",
        "status": "UNDER CONSTRUCTION, RESALE",
        "description": "Well maintained facilities, spacious and ventilated space for accommodation. Every floor has a single flat only so consumer privacy is what make this property unique.",
    },
    {
        "name": "Glentree pharma county",
        "type": "Residential Land",
        "city": "Hyderabad",
        "locality": "Yacharam",
        "bhk": "N/A",
        "area": "1649 sq.ft.",
        "price": "₹17.41 Lakh",
        "furnish": "Unfurnished",
        "status": "EAST FACING, DTCP APPROVED, IN GATED COMMUNITY, READY TO MOVE, RESALE",
        "description": "Glentree homes 70acers mega layout open plots sagar highway hyderabad  Project summary  Phase 1 36 acres County 1 48 plots County 2 456 plots  Dtcp approved  Rera approved Spot registrations   Project highlights Street lights in the entire layout Over head tank water supply from oht to every plot 24",
    },
    {
        "name": "Fortuna towers",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Mokila",
        "bhk": "4BHK",
        "area": "2715 sq.ft.",
        "price": "₹1.25 Crore",
        "furnish": "Furnished",
        "status": "UNDER CONSTRUCTION, RESALE",
        "description": "High-Rise 4 bedroom ,2715 sq ft apartment nearing completion with premium amenities included such as gypsum false roof, ample 3 level basement parking,fireproofing in all rooms, central gas connection, imported aluminum windows, high-Quality dura doors, grohe c to name a few on mokila main road, for",
    },
    {
        "name": "Navya Prestiage",
        "type": "Independent House/Villa",
        "city": "Hyderabad",
        "locality": "Indresham",
        "bhk": "2BHK",
        "area": "1530 sq.ft.",
        "price": "₹1.04 Crore",
        "furnish": "Furnished",
        "status": "READY TO MOVE, RESALE, RERA",
        "description": "Excellent construction*navya tulasi gardens* - Gated community - Hmda approved, 150 sq yards - West facing - Spread over 10 acres - Just adjacent to 100ft main road - 5 mins away from patancheru - 2 mins away from orr - 6 mins to silver oaks international school - 25 mins drive to gachibowli - 30\\' a",
    },
    {
        "name": "New project padmavathy",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Nagole",
        "bhk": "3BHK",
        "area": "1900 sq.ft.",
        "price": "₹91.2 Lakh",
        "furnish": "Unfurnished",
        "status": "UNDER CONSTRUCTION, RESALE",
        "description": "Situated in nagole, hyderabad, new project padmavathy is a well planned society that offers a pleasant living experience to its residents. This 3 bhk flat in hyderabad is your opportunity to be a part of this community. The flat is over 1900 sq.Ft. Built up area and comes with 3 bedroom(s), 3 bathro",
    },
    {
        "name": "Akshitha Imperial City",
        "type": "Residential Land",
        "city": "Hyderabad",
        "locality": "Adibatla",
        "bhk": "N/A",
        "area": "1503-2700  sq.ft.",
        "price": "₹81 Lakh",
        "furnish": "Unfurnished",
        "status": "READY TO MOVE, NEW BOOKING",
        "description": "Akshitha imperial city in adibatla, hyderabad by akshita infra is a residential project.  The project offers land with perfect combination of contemporary architecture and features to provide comfortable living.    The size of the land is from 139.63 sq. Mt to 836.12 sq. Mt    The project is vastu c",
    },
    {
        "name": "Carlton Creek",
        "type": "Residential Apartment",
        "city": "Hyderabad",
        "locality": "Khajaguda",
        "bhk": "3BHK",
        "area": "1384 sq.ft.",
        "price": "₹1.45 Crore",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "East facing corner property with good woodwork.",
    },
    {
        "name": "Srika Green Oasis",
        "type": "Residential Land",
        "city": "Hyderabad",
        "locality": "Kollur",
        "bhk": "N/A",
        "area": "1800 sq.ft.",
        "price": "₹63 Lakh",
        "furnish": "Unfurnished",
        "status": "CORNER PROPERTY, AUTHORITY APPROVED, IN GATED COMMUNITY, UNDER CONSTRUCTION, RESALE, RERA",
        "description": "Hi sir/madam,    \"srika green oasis project@bhanoor\"   Project description: \" srika green oasis project\" is one of the popular residential developments in bhanoor neighborhood of hyderabad. It is among the upcoming projects of its class. It has lavish yet thoughtfully designed residences. The destin",
    },
    {
        "name": "Ashray Residency",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "Picnic Garden",
        "bhk": "3BHK",
        "area": "946 sq.ft.",
        "price": "₹50 Lakh",
        "furnish": "Furnished",
        "status": "READY TO MOVE, RESALE",
        "description": "This is your chance to own a 3 bhk residential apartment in ashray residency, picnic garden, kolkata south, kolkata where luxury comes with affordability. Basic details: You will love this bright and spacious 3 bedroom apartment with 2 bathrooms, modular kitchen, spacious hall and 1 balcony. The bal",
    },
    {
        "name": "Classic Enclave",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "New Ballygunge",
        "bhk": "2BHK",
        "area": "900 sq.ft.",
        "price": "₹58 Lakh",
        "furnish": "Furnished",
        "status": "READY TO MOVE, RESALE",
        "description": "It is near to garden high school, delhi public school ,acropolis ,ruby desun hospital and just behind kasba police station",
    },
    {
        "name": "Sashwaat Mandeville Garden Court 3",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "Ballygunge",
        "bhk": "3BHK",
        "area": "1972 sq.ft.",
        "price": "₹2.1 Crore",
        "furnish": "Furnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Mandeville, near south point high school, flat in well maintained complex in peaceful location, g 11 building,i have 5 option in same tower on upper floor , 9th & 10th floor, 3 bhk, 3 toilets & each flat having 3 parking (2 mechanical parking and 1 open parking). Rooms are in big size & each room ha",
    },
    {
        "name": "Green Heights II",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "Majarhati",
        "bhk": "3BHK",
        "area": "814 sq.ft.",
        "price": "₹76 Lakh",
        "furnish": "Furnished",
        "status": "UNDER CONSTRUCTION, RESALE",
        "description": "1.5 km from eco park. On rajarhat main road green heights ii rajarhat",
    },
    {
        "name": "Ideal Abasan",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "Rajarhat",
        "bhk": "2BHK",
        "area": "860 sq.ft.",
        "price": "₹31 Lakh",
        "furnish": "Furnished",
        "status": "READY TO MOVE, RESALE",
        "description": "South facing topfloor top of the world, full of light and air",
    },
    {
        "name": "Guddi Apartments",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "Sakher Bazar",
        "bhk": "2BHK",
        "area": "650 sq.ft.",
        "price": "₹23 Lakh",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Located in the popular residential address of sakher bazar, kolkata south, guddi apartments is one of the most preferred destination for apartments in kolkata south. This 2 bhk flat is your ticket to be a part of this community. The flat is over 650 sq.Ft. Carpet area and comes with 2 bedroom(s), 1 ",
    },
    {
        "name": "Jindal Heights",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "Liluah",
        "bhk": "2BHK",
        "area": "1000 sq.ft.",
        "price": "₹45 Lakh",
        "furnish": "Furnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Check out this 2 bhk apartment for sale in jindal heights, a popular residential project that houses in-Demand flats in liluah, kolkata west. Containing 2 bedroom(s), 1 bathroom and 1 balcony, this flat is spread over a built up area of 1000 sq.Ft. This flat lies on the 2nd level of a 4 storey build",
    },
    {
        "name": "kali PARK",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "Rajarhat",
        "bhk": "1BHK",
        "area": "565 sq.ft.",
        "price": "₹13.25 Lakh",
        "furnish": "Furnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Exact location:- Narayanpur near vidyasagar matrisadan hospital / narayanpur ps . 1bhk flat for sale near kali park Very close to newtown ,airport. Vishal megamart very close. Various schools nearby. 24*7 water supply.",
    },
    {
        "name": "Tirath Guru",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "Bangur",
        "bhk": "3BHK",
        "area": "1239-1254  sq.ft.",
        "price": "₹70.22 Lakh",
        "furnish": "Unfurnished",
        "status": "READY TO MOVE, NEW BOOKING",
        "description": "Enjoy a blissful living experience in Tirath Guru. This residential project encompasses 3 BHK flats in Bangur, Kolkata North and brings you the best of both the worlds – excellent aesthetics and exemplary lifestyle.  Its unique highlights include facilities like 24/7 Power Backup, 24x7 Security, Gat",
    },
    {
        "name": "Standalone Apartment",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "Jodhpur Garden",
        "bhk": "3BHK",
        "area": "1000 sq.ft.",
        "price": "₹30 Lakh",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "The flat is on the 3rd floor without lift and is built on colony land. Hence loans would only be available from nbfc\\'s - Non banking finance companies. Only serious parties are welcome.   Nestled in the heart of south kolkata, just a 5 mins walk away from lords bakery more and near to lake gardens a",
    },
    {
        "name": "BGA Amrita Abashan 1",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "Sonarpur",
        "bhk": "1BHK",
        "area": "466 sq.ft.",
        "price": "₹13.7 Lakh",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Pollution free with a peaceful area. Fully furnished flat with garage. Price is negotiable.",
    },
    {
        "name": "Silver Spring",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "EM Bypass",
        "bhk": "3BHK",
        "area": "1755 sq.ft.",
        "price": "₹1.99 Crore",
        "furnish": "Furnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Apartment for sale in silver spring on em byepass  Whatsapp only  Bright, airy 9th floor flat with a view of green fields. 3 freshly renovated bathrooms with new piping. 3 cheerful bedrooms with lots of light and a view  1 large living/dining, with a balcony and a beautiful view  1 bright long kitch",
    },
    {
        "name": "Realtech Rajotto",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "Rajarhat",
        "bhk": "3BHK",
        "area": "898-958  sq.ft.",
        "price": "₹32.57 Lakh",
        "furnish": "Unfurnished",
        "status": "UNDER CONSTRUCTION, NEW BOOKING, RERA | HIRA",
        "description": "Experience a new style of living with Realtech Rajotto. The project offers an exclusive range of 3 BHK flats in Rajarhat, Kolkata East at a price range of Rs. 30.53 Lac - Rs. 32.57 Lac.  These flats have a super built-up area ranging from 898.0 sq. ft. - 958.0sq. ft. It is an under construction proj",
    },
    {
        "name": "Saarbian Bhaba Shanti",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "Naktala",
        "bhk": "2BHK",
        "area": "865 sq.ft.",
        "price": "₹37 Lakh",
        "furnish": "Furnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Located in the popular residential address of naktala, kolkata south, saarbian bhaba shanti is one of the most preferred destination for apartments in kolkata south. This 2 bhk flat is your ticket to be a part of this community. The flat is facing the east direction. The floor plan additionally cont",
    },
    {
        "name": "Janapriyo Park Nepalgunge Rd",
        "type": "Residential Land",
        "city": "Kolkata",
        "locality": "Bishnupur",
        "bhk": "N/A",
        "area": "3599 sq.ft.",
        "price": "₹30 Lakh",
        "furnish": "Unfurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "Plot for sale in bishnupur is available in kolkata south. This locality resonates with your modern lifestyle. It spreads over 5 kottah super built up area. This property allows you to construct upto 3 floors. The property is guarded and secluded by boundary wall around it. Expected possession of pro",
    },
    {
        "name": "Suncrest Estate",
        "type": "Residential Apartment",
        "city": "Kolkata",
        "locality": "Rajpur",
        "bhk": "3BHK",
        "area": "1033-1465  sq.ft.",
        "price": "₹60.06 Lakh",
        "furnish": "Unfurnished",
        "status": "UNDER CONSTRUCTION, NEW BOOKING, RERA | HIRA",
        "description": "Book your 3 BHK flat in Suncrest Estate, Rajpur, Kolkata South. Having a super built-up area of 1033.0 sq. ft. - 1465.0 sq. ft., these flats promise an exclusive view and refreshing vibes, making them well ventilated.  It is a superbly design project set amidst excellent surroundings and offers resi",
    },
    {
        "name": "Puraniks Tokyo Bay",
        "type": "Residential Apartment",
        "city": "Mumbai",
        "locality": "Kasar vadavali",
        "bhk": "2BHK",
        "area": "667-683  sq.ft.",
        "price": "₹85.76 Lakh",
        "furnish": "Unfurnished",
        "status": "UNDER CONSTRUCTION, NEW LAUNCH, NEW BOOKING, RERA",
        "description": "Puraniks Tokyo Bay is a new launch project, offering 2 BHK flats in Kasar vadavali, Thane. These flats have a carpet area in the range of 667.0 sq. ft. to 683.0 sq. ft. and are available at an economical price of Rs. 83.76 Lac - Rs. 85.76 Lac.  It is well connected to the city areas and features a l",
    },
    {
        "name": "Hiranandani Gardens Glen Height",
        "type": "Residential Apartment",
        "city": "Mumbai",
        "locality": "Hiranandani Gardens Powai",
        "bhk": "3BHK",
        "area": "1470 sq.ft.",
        "price": "₹5.5 Crore",
        "furnish": "Unfurnished",
        "status": "READY TO MOVE, NEW BOOKING",
        "description": "Make Hiranandani Gardens Glen Height your next home. This project offers 3 BHK flats in Hiranandani Gardens Powai, Central Mumbai suburbs. With a super built-up area ranging from 1470.0 sq. ft. to 1470.0 sq. ft., these flats combine the finest design and amenities in Central Mumbai suburbs to provid",
    },
    {
        "name": "Arihant Anmol",
        "type": "Residential Apartment",
        "city": "Mumbai",
        "locality": "Badlapur East",
        "bhk": "2BHK",
        "area": "438-461  sq.ft.",
        "price": "₹35.96 Lakh",
        "furnish": "Unfurnished",
        "status": "UNDER CONSTRUCTION, NEW BOOKING, RERA",
        "description": "This well-known project offers 2 BHK apartments in Badlapur East, Mumbai Beyond Thane. With a carpet area, ranging from 438.0 sq. ft. to 461.0 sq. ft., the apartments are available at an economical price range of Rs. 34.16 Lac to Rs. 35.96 Lac.  There are 20 towers. A close attention has been paid t",
    },
    {
        "name": "Shreejee Passcode Paradise",
        "type": "Residential Apartment",
        "city": "Mumbai",
        "locality": "Mulund West",
        "bhk": "3BHK",
        "area": "802-964  sq.ft.",
        "price": "₹2.3 Crore",
        "furnish": "Unfurnished",
        "status": "UNDER CONSTRUCTION, NEW LAUNCH, NEW BOOKING, RERA",
        "description": "Experience a new style of living with Shreejee Passcode Paradise. The project offers an exclusive range of 3 BHK flats in Mulund West, Central Mumbai suburbs at a price range of Rs. 1.92 Crore - Rs. 2.3 Crore.  These flats have a carpet area ranging from 802.0 sq. ft. - 964.0sq. ft. It is a new laun",
    },
    {
        "name": "Nahars Amrit Shakti",
        "type": "Residential Apartment",
        "city": "Mumbai",
        "locality": "Chandivali",
        "bhk": "2BHK",
        "area": "870 sq.ft.",
        "price": "₹2.1 Crore",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "We are the proud owners of this 2 bhk apartment available in srishti synchronicity, lok milan colony, central mumbai suburbs. This furnished apartment it is a and the unit is located on 2nd floor and has a carpet area of 870 sq.Ft. . It has 2 bathroom(s) and 2 balcony(s). The ownership is freehold t",
    },
    {
        "name": "Shankeshwar Nagar CHS",
        "type": "Residential Apartment",
        "city": "Mumbai",
        "locality": "Dombivli East",
        "bhk": "1BHK",
        "area": "615 sq.ft.",
        "price": "₹32 Lakh",
        "furnish": "Semifurnished",
        "status": "READY TO MOVE, RESALE",
        "description": "House plus other additional furniture and electronic appliances along with it. Cool place to live. No pollution in air.  10-15 min drive from station. Less crowded. People are simple,nice, helping.",
    },
    {
        "name": "Suryoday Apartment",
        "type": "Residential Apartment",
        "city": "Mumbai",
        "locality": "New Prabhadevi Road",
        "bhk": "1BHK",
        "area": "280 sq.ft.",
        "price": "₹89.99 Lakh",
        "furnish": "Furnished",
        "status": "READY TO MOVE, RESALE",
        "description": "This is your chance to own a 1 bhk residential apartment in suryoday apartment, century bazaar, south mumbai, mumbai where luxury comes with affordability. Basic details: You will love this bright and spacious 1-Bedroom apartment with 1 bathroom. This house provides ample natural light and has good ",
    },
    {
        "name": "Sai Proviso Icon",
        "type": "Residential Apartment",
        "city": "Mumbai",
        "locality": "Roadpali",
        "bhk": "1BHK",
        "area": "454 sq.ft.",
        "price": "₹61 Lakh",
        "furnish": "Unfurnished",
        "status": "UNDER CONSTRUCTION, NEW BOOKING, RERA",
        "description": "Experience a new style of living with Sai Proviso Icon. The project offers an exclusive range of 1 BHK flats in Roadpali, Navi Mumbai at a price range of Rs. 61 Lac - Rs. 61 Lac.  These flats have a carpet area ranging from 454.0 sq. ft. - 454.0sq. ft. It is an under construction project. The design",
    },
    {
        "name": "Sheth Montana",
        "type": "Residential Apartment",
        "city": "Mumbai",
        "locality": "Mulund West",
        "bhk": "2BHK",
        "area": "611-902  sq.ft.",
        "price": "₹2.5 Crore",
        "furnish": "Unfurnished",
        "status": "UNDER CONSTRUCTION, NEW BOOKING, RERA",
        "description": "Sheth Montana is an under construction project, offering 2 BHK flats in Mulund West, Central Mumbai suburbs. These flats have a carpet area in the range of 611.0 sq. ft. to 902.0 sq. ft. and are available at an economical price of Rs. 1.54 Crore - Rs. 2.5 Crore.  It is well connected to the city are",
    },
]

def format_properties_for_prompt() -> str:
    """Compact one-line-per-property to stay within token limits."""
    lines = ["name | city | locality | type | bhk | area | price | furnish | status"]
    for p in PROPERTIES:
        row = (
            str(p.get("name","")) + " | " + str(p.get("city","")) + " | " +
            str(p.get("locality","")) + " | " + str(p.get("type","")) + " | " +
            str(p.get("bhk","")) + " | " + str(p.get("area","")) + " | " +
            str(p.get("price","")) + " | " + str(p.get("furnish","")) + " | " +
            str(p.get("status",""))
        )
        lines.append(row)
    return chr(10).join(lines)
